import React, { useState, useEffect } from 'react'
import { Loader, Card, FormField } from '../components'
const RenderCards = ({ data, title }) => {
    //if data.length>0 then we have to map over all of the data and then render all of the cards while passing all posts data to each ondividual card
    if (data.length > 0) {

        return data.map((post) => <Card key={post._id} {...post} />)
    }
    return (
        <h2 className='mt-5 font-bold uppercase text-[#6449ff] text-xl'>{title}</h2>
    )
}
const Home = () => {
    const [loading, setLoading] = useState(false);
    const [allPosts, setAllPosts] = useState(null);
    const [searchText, setSearchText] = useState('hello');
    return (
        <div>
            <section className='max-w-7xl mx-auto'>
                <div>
                    <h1 className='font-extrabold text-[#222328] text-[32px] '>Community Showcase</h1>
                    <p className='mt-2 text-[#666e75] text-[16px] max-w-[700px] '>Browse through an imaginative and visually stunning images generated by DALL-E AI</p>
                </div>
                <div className='mt-16'>
                    <FormField />
                </div>
                <div className='mt-10'>
                    {
                        loading ? (
                            <div className='flex justify-center items-center'><Loader /></div>
                        ) : (
                            <>
                                {searchText && (
                                    <h2 className='font-medium text-[#666e75' text-xl mb-3>
                                        Showing results for <span className='text-[#222328] font-bold'>{searchText}</span>
                                    </h2>
                                )}
                                <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
                                    {/* if there is a search text then render whatever searched data is (and if there is no search results then provide a title that no search ressult has been found)but if nothing is searched and we want to show all the posts then we have to again render the card and display all the results (display no posts found if there are actualy no posts) */}
                                    {searchText?(
                                        <RenderCards data={[]} title="No search result found" />
                                    ):(
                                        <RenderCards data={[]} title="No Posts found "/>
                                    )}
                                </div>
                            </>
                        )
                    }
                </div>
            </section>
        </div>
    )
}

export default Home
